TrajectoryPlannerROS:
    acc_lim_x: 2.5
    #acc_lim_theta: 3.2
    max_vel_x: 0.9
    min_vel_x: 0.0
    max_vel_theta: 1.7
    min_vel_theta: -1.7
    min_in_place_vel_theta: 0.3
    holonomic_robot: false
    yaw_goal_tolerance: 0.5
    xy_goal_tolerance: 0.4
    pdist_scale: 0.8
    gdist_scale: 0.8
    #occdist_scale: 0.04
    occdist_scale: 0.05
    escape_vel: 0.0
    meter_scoring: true
