# move_base common parameters
# + 2021 Tsudanuma Challenge
# + 2021 Tsukuba Challenge
# Configuration by NaokiTakahashi12
GlobalPlanner:
  allow_unknown: true
  default_tolerance: 5
  planner_window_x: 0
  planner_window_y: 0
  orientation_window_size: 2
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  orientation_mode: 2
  lethal_cost: 128
  cost_factor: 0.6
  neutral_cost: 55.0
  visualize_potential: false
  publish_potential: false
