# move_base common parameters
# + 2021 Tsudanuma Challenge
# + 2021 Tsukuba Challenge
# Configuration by NaokiTakahashi12
TrajecotryPlannerROS:
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta: 3.2
  max_vel_x: 1.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4
  escape_vel: -0.1
  holonomic_robot: false
  y_vels: [-0.3, -0.1, 0.1, 0.3]
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false
  sim_time: 1.0
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 3
  vtheta_samples: 20
  meter_scoring: false
  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.01
  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.8
  dwa: false
  publish_cost_grid_pc: false
  global_frame_id: odom
  oscillation_reset_dist: 0.05
  prune_plan: true
